window.EVENT_DATA = {
  "event": {
    "name": "BAPS NA Communications MidYear Meeting",
    "location": "Dallas, Texas",
    "dates": "Update with meeting dates",
    "notes": [
      "Imported from Comms Mid-Year Retreat Registration (Responses).xlsx.",
      "The dashboard keeps all responses, and logistics teams can filter to confirmed attendees."
    ]
  },
  "attendees": [
    {
      "id": 1,
      "name": "Rakhee Patel",
      "city": "",
      "role": "Behno",
      "phone": "281-509-0977",
      "email": "patel.rakhee.c@gmail.com",
      "bapsEmail": "rp4317810@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "To Go",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 2,
      "name": "Sunayna Bhikha",
      "city": "",
      "role": "Behno",
      "phone": "904-576-8030",
      "email": "sunaynabhikha@gmail.com",
      "bapsEmail": "sb1189001@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "Needs hotel to mandir transport",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 3,
      "name": "Dhwani Shah",
      "city": "",
      "role": "Behno",
      "phone": "909-261-5752",
      "email": "dhwanis990@gmail.com",
      "bapsEmail": "dt9131933@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Vegan",
      "foodNotes": "Vegan",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "None",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 4,
      "name": "Rameshvari Patel (Meesha)",
      "city": "",
      "role": "Behno",
      "phone": "832-388-9962",
      "email": "rameshvari.patel@gmail.com",
      "bapsEmail": "rp1932001@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 5,
      "name": "Shivani Kanji",
      "city": "",
      "role": "Behno",
      "phone": "904-576-8029",
      "email": "shivi88@gmail.com",
      "bapsEmail": "sk7418001@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 6,
      "name": "Palak Shah",
      "city": "",
      "role": "Behno",
      "phone": "908-358-4807",
      "email": "palakshah80@gmail.com",
      "bapsEmail": "ps0428001@na.baps.id",
      "arrivalAirport": "DFW",
      "arrivalDate": "2026-04-30 00:00",
      "arrivalTime": "18:48",
      "arrivalFlight": "Spirit (NK 2701)",
      "arrivalFlightIdent": "NK2701",
      "departureAirport": "DFW",
      "departureDate": "2026-05-03 00:00",
      "departureTime": "10:21",
      "departureFlight": "Spirit (NK 2700)",
      "departureFlightIdent": "NK2700",
      "airportNeed": "Needs pickup / dropoff",
      "driverGroup": "DFW | 2026-04-30 00:00 | 18:48",
      "mealPreference": "Mushrooms/Pineapple",
      "foodNotes": "Mushrooms/Pineapple",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "TBD",
      "airportDropoffContact": "TBD",
      "dinnerThursday": "To Go",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "To Go",
      "notes": "Stay: I will make my own accommodation arrangements | Pickup contact: TBD | Dropoff contact: TBD"
    },
    {
      "id": 7,
      "name": "Chaitali Inamdar",
      "city": "",
      "role": "Behno",
      "phone": "732-535-3767",
      "email": "chaitaliinamdar@gmail.com",
      "bapsEmail": "ci3767230@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 8,
      "name": "Milli Patel",
      "city": "",
      "role": "Behno",
      "phone": "510-365-0232",
      "email": "milli.j.patel@gmail.com",
      "bapsEmail": "mp0232001@na.baps.id",
      "arrivalAirport": "DFW",
      "arrivalDate": "2026-05-01 00:00",
      "arrivalTime": "08:31",
      "arrivalFlight": "Spirit 1620",
      "arrivalFlightIdent": "1620",
      "departureAirport": "DFW",
      "departureDate": "2026-05-03 00:00",
      "departureTime": "06:02",
      "departureFlight": "American Airlines (AA 1360)",
      "departureFlightIdent": "AA1360",
      "airportNeed": "Needs pickup / dropoff",
      "driverGroup": "DFW | 2026-05-01 00:00 | 08:31",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "Needs hotel to mandir transport",
      "hotel": "Embassy Suites by Hilton Dallas DFW Airport South",
      "rooming": "[Staying with Krishna]",
      "status": "Confirmed",
      "accommodation": "I would like to stay in a hotel (To be booked directly with hotel using discount link provided)",
      "airportPickupContact": "TBD",
      "airportDropoffContact": "TBD",
      "dinnerThursday": "None",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "To Go",
      "notes": "Stay: I would like to stay in a hotel (To be booked directly with hotel using discount link provided) | Pickup contact: TBD | Dropoff contact: TBD"
    },
    {
      "id": 9,
      "name": "Krishna Trambadia",
      "city": "",
      "role": "Behno",
      "phone": "908-358-7958",
      "email": "ktrambadia@gmail.com",
      "bapsEmail": "ktrambadia@gmail.com",
      "arrivalAirport": "DFW",
      "arrivalDate": "2026-04-30 00:00",
      "arrivalTime": "22:59",
      "arrivalFlight": "American Airlines (AA 3186)",
      "arrivalFlightIdent": "AA3186",
      "departureAirport": "DFW",
      "departureDate": "2026-05-03 00:00",
      "departureTime": "05:00",
      "departureFlight": "American Airlines (AA 1044)",
      "departureFlightIdent": "AA1044",
      "airportNeed": "Needs pickup / dropoff",
      "driverGroup": "DFW | 2026-04-30 00:00 | 22:59",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "Needs hotel to mandir transport",
      "hotel": "Embassy Suites by Hilton Dallas DFW Airport South",
      "rooming": "92388462",
      "status": "Confirmed",
      "accommodation": "I would like to stay in a hotel (To be booked directly with hotel using discount link provided)",
      "airportPickupContact": "TBD",
      "airportDropoffContact": "TBD",
      "dinnerThursday": "To Go",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "To Go",
      "notes": "Stay: I would like to stay in a hotel (To be booked directly with hotel using discount link provided) | Pickup contact: TBD | Dropoff contact: TBD"
    },
    {
      "id": 10,
      "name": "Ami Patel",
      "city": "",
      "role": "Behno",
      "phone": "703-627-1831",
      "email": "ianandami@gmail.com",
      "bapsEmail": "ap7031001@na.baps.id",
      "arrivalAirport": "DAL",
      "arrivalDate": "2026-04-30 00:00",
      "arrivalTime": "19:00",
      "arrivalFlight": "Southwest (SW 1738)",
      "arrivalFlightIdent": "SW1738",
      "departureAirport": "DFW",
      "departureDate": "2026-05-03 00:00",
      "departureTime": "07:20",
      "departureFlight": "United (UAL 2639)",
      "departureFlightIdent": "UAL2639",
      "airportNeed": "Needs pickup / dropoff",
      "driverGroup": "DAL | 2026-04-30 00:00 | 19:00",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "Needs hotel to mandir transport",
      "hotel": "Embassy Suites by Hilton Dallas DFW Airport South",
      "rooming": "53088246",
      "status": "Confirmed",
      "accommodation": "I would like to stay in a hotel (To be booked directly with hotel using discount link provided)",
      "airportPickupContact": "TBD",
      "airportDropoffContact": "TBD",
      "dinnerThursday": "To Go",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "To Go",
      "notes": "Stay: I would like to stay in a hotel (To be booked directly with hotel using discount link provided) | Pickup contact: TBD | Dropoff contact: TBD"
    },
    {
      "id": 11,
      "name": "dhawal tank",
      "city": "",
      "role": "Bhaiyo",
      "phone": "909-288-9975",
      "email": "dpvtank@gmail.com",
      "bapsEmail": "dt7121921@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Vegan",
      "foodNotes": "Vegan",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "None",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 12,
      "name": "Yogesh Patel",
      "city": "",
      "role": "Bhaiyo",
      "phone": "732-207-4721",
      "email": "ynp381@gmail.com",
      "bapsEmail": "yp0403810@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "To Go",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 13,
      "name": "Tushar Solanki",
      "city": "",
      "role": "Bhaiyo",
      "phone": "214-289-3252",
      "email": "tsolanki@gmail.com",
      "bapsEmail": "ts3252001@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 14,
      "name": "Kashyap Patel",
      "city": "",
      "role": "Bhaiyo",
      "phone": "678-897-1546",
      "email": "tikubpatel@gmail.com",
      "bapsEmail": "KP1976008@na.baps.id",
      "arrivalAirport": "DFW",
      "arrivalDate": "2026-04-30 00:00",
      "arrivalTime": "22:08",
      "arrivalFlight": "Delta (DAL 0031)",
      "arrivalFlightIdent": "DAL0031",
      "departureAirport": "DAL",
      "departureDate": "2026-05-03 00:00",
      "departureTime": "10:17",
      "departureFlight": "Delta (DAL 0441)",
      "departureFlightIdent": "DAL0441",
      "airportNeed": "Needs pickup / dropoff",
      "driverGroup": "DFW | 2026-04-30 00:00 | 22:08",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "Needs hotel to mandir transport",
      "hotel": "Embassy Suites by Hilton Dallas DFW Airport South",
      "rooming": "90807132",
      "status": "Confirmed",
      "accommodation": "I would like to stay in a hotel (To be booked directly with hotel using discount link provided)",
      "airportPickupContact": "TBD",
      "airportDropoffContact": "TBD",
      "dinnerThursday": "To Go",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "To Go",
      "notes": "Stay: I would like to stay in a hotel (To be booked directly with hotel using discount link provided) | Pickup contact: TBD | Dropoff contact: TBD"
    },
    {
      "id": 15,
      "name": "Darshan Patel",
      "city": "",
      "role": "Bhaiyo",
      "phone": "919-332-3782",
      "email": "darshp1@gmail.com",
      "bapsEmail": "cm.ndc14@na.baps.org",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 16,
      "name": "Mitesh Patel",
      "city": "",
      "role": "Bhaiyo",
      "phone": "678-458-6447",
      "email": "patelmiteshj@gmail.com",
      "bapsEmail": "cm.sanyojak@na.baps.org",
      "arrivalAirport": "DAL",
      "arrivalDate": "2026-04-30 00:00",
      "arrivalTime": "13:05",
      "arrivalFlight": "Southwest (SW 3913)",
      "arrivalFlightIdent": "SW3913",
      "departureAirport": "N/A",
      "departureDate": "N/A",
      "departureTime": "N/A",
      "departureFlight": "N/A",
      "departureFlightIdent": "",
      "airportNeed": "Needs pickup / dropoff",
      "driverGroup": "DAL | 2026-04-30 00:00 | 13:05",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "Needs hotel to mandir transport",
      "hotel": "Embassy Suites by Hilton Dallas DFW Airport South",
      "rooming": "N/A",
      "status": "Confirmed",
      "accommodation": "I would like to stay in a hotel (To be booked directly with hotel using discount link provided)",
      "airportPickupContact": "TBD",
      "airportDropoffContact": "TBD",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "To Go",
      "breakfastSunday": "None",
      "notes": "Stay: I would like to stay in a hotel (To be booked directly with hotel using discount link provided) | Pickup contact: TBD | Dropoff contact: TBD"
    },
    {
      "id": 17,
      "name": "Viral Desai",
      "city": "",
      "role": "Bhaiyo",
      "phone": "832-498-4725",
      "email": "mandirmedia@gmail.com",
      "bapsEmail": "vd2525001@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "To Go",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 18,
      "name": "Naimik Patel",
      "city": "",
      "role": "Bhaiyo",
      "phone": "864-382-7326",
      "email": "naimik@sevaks.co",
      "bapsEmail": "cm.cc1@na.baps.org",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "Mandir",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 19,
      "name": "Siddharth Dubal",
      "city": "",
      "role": "Bhaiyo",
      "phone": "646-842-2500",
      "email": "siddh@janusrecruit.com",
      "bapsEmail": "sd1017120@na.baps.org",
      "arrivalAirport": "DFW",
      "arrivalDate": "2026-04-30 00:00",
      "arrivalTime": "22:59",
      "arrivalFlight": "American Airlines (AA 3186)",
      "arrivalFlightIdent": "AA3186",
      "departureAirport": "DFW",
      "departureDate": "2026-05-02 00:00",
      "departureTime": "20:15",
      "departureFlight": "American Airlines (AA 2409)",
      "departureFlightIdent": "AA2409",
      "airportNeed": "Needs pickup / dropoff",
      "driverGroup": "DFW | 2026-04-30 00:00 | 22:59",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "Needs hotel to mandir transport",
      "hotel": "Embassy Suites by Hilton Dallas DFW Airport South",
      "rooming": "[Staying with Mitesh]",
      "status": "Confirmed",
      "accommodation": "I would like to stay in a hotel (To be booked directly with hotel using discount link provided)",
      "airportPickupContact": "TBD",
      "airportDropoffContact": "TBD",
      "dinnerThursday": "To Go",
      "dinnerSaturday": "To Go",
      "breakfastSunday": "None",
      "notes": "Stay: I would like to stay in a hotel (To be booked directly with hotel using discount link provided) | Pickup contact: TBD | Dropoff contact: TBD"
    },
    {
      "id": 20,
      "name": "Purav Patel",
      "city": "",
      "role": "Bhaiyo",
      "phone": "832-646-8292",
      "email": "puravp05@gmail.com",
      "bapsEmail": "pp6468292@na.baps.id",
      "arrivalAirport": "",
      "arrivalDate": "",
      "arrivalTime": "",
      "arrivalFlight": "",
      "arrivalFlightIdent": "",
      "departureAirport": "",
      "departureDate": "",
      "departureTime": "",
      "departureFlight": "",
      "departureFlightIdent": "",
      "airportNeed": "No airport transfer needed",
      "driverGroup": "Self-arranged",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "No hotel shuttle needed",
      "hotel": "Self-arranged",
      "rooming": "",
      "status": "Confirmed",
      "accommodation": "I will make my own accommodation arrangements",
      "airportPickupContact": "",
      "airportDropoffContact": "",
      "dinnerThursday": "None",
      "dinnerSaturday": "To Go",
      "breakfastSunday": "None",
      "notes": "Stay: I will make my own accommodation arrangements"
    },
    {
      "id": 21,
      "name": "Jamin Brahmbhatt",
      "city": "",
      "role": "Bhaiyo",
      "phone": "901-896-9575",
      "email": "jaminbrahmbhatt@gmail.com",
      "bapsEmail": "jb8969575@na.baps.id",
      "arrivalAirport": "DFW",
      "arrivalDate": "2026-05-01 00:00",
      "arrivalTime": "07:58",
      "arrivalFlight": "Frontier (F9 4017)",
      "arrivalFlightIdent": "F94017",
      "departureAirport": "DFW",
      "departureDate": "2026-05-03 00:00",
      "departureTime": "12:23",
      "departureFlight": "Frontier (F9 1482)",
      "departureFlightIdent": "F91482",
      "airportNeed": "Needs pickup / dropoff",
      "driverGroup": "DFW | 2026-05-01 00:00 | 07:58",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "Needs hotel to mandir transport",
      "hotel": "Embassy Suites by Hilton Dallas DFW Airport South",
      "rooming": "[Staying with Kashyap]",
      "status": "Confirmed",
      "accommodation": "I would like to stay in a hotel (To be booked directly with hotel using discount link provided)",
      "airportPickupContact": "TBD",
      "airportDropoffContact": "TBD",
      "dinnerThursday": "None",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "To Go",
      "notes": "Stay: I would like to stay in a hotel (To be booked directly with hotel using discount link provided) | Pickup contact: TBD | Dropoff contact: TBD"
    },
    {
      "id": 22,
      "name": "Jitan Patel",
      "city": "",
      "role": "Bhaiyo",
      "phone": "678-471-6702",
      "email": "jitanpatel@gmail.com",
      "bapsEmail": "jitanpatel@gmail.com",
      "arrivalAirport": "DFW",
      "arrivalDate": "2026-05-01 00:00",
      "arrivalTime": "16:18",
      "arrivalFlight": "Frontier (F9 1475)",
      "arrivalFlightIdent": "F91475",
      "departureAirport": "DFW",
      "departureDate": "2026-05-03 00:00",
      "departureTime": "06:28",
      "departureFlight": "Frontier (F9 1476)",
      "departureFlightIdent": "F91476",
      "airportNeed": "Needs pickup / dropoff",
      "driverGroup": "DFW | 2026-05-01 00:00 | 16:18",
      "mealPreference": "Standard vegetarian",
      "foodNotes": "",
      "transportationNeed": "Needs hotel to mandir transport",
      "hotel": "Embassy Suites by Hilton Dallas DFW Airport South",
      "rooming": "52056051",
      "status": "Confirmed",
      "accommodation": "I would like to stay in a hotel (To be booked directly with hotel using discount link provided)",
      "airportPickupContact": "TBD",
      "airportDropoffContact": "TBD",
      "dinnerThursday": "None",
      "dinnerSaturday": "Mandir",
      "breakfastSunday": "To Go",
      "notes": "Stay: I would like to stay in a hotel (To be booked directly with hotel using discount link provided) | Pickup contact: TBD | Dropoff contact: TBD"
    }
  ]
};
